---
title: "Monkey Pox Analysis"
format: html
editor: visual
---

# Monkey Pox Analysis (WHO/Our World In Data)

```{r}
rm(list=ls())
library(tidyverse)
library(janitor)
library(scales)
```

# Load and Summarize Data

```{r}
monkey <- read_csv("./monkeypox.csv") |> select(location,iso_code,date,total_cases,total_deaths,
                          new_cases,new_deaths,new_cases_smoothed,
                          new_deaths_smoothed) |> mutate(yr = lubridate::year(date))

```

# Total and Daily Cases Worldwide by Date

```{r}
world <- monkey |> filter(location =="World")
summary(world$total_cases)
```

```{r}
summary(world$new_cases)
```

```{r}
world |> ggplot() + geom_point(aes(x=date,y=total_cases,col=total_cases)) +
  labs(title="Total Monkey Pox Cases Worldwide") +
   theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
world |> ggplot() + geom_line(aes(x=date,y=new_cases,fill=location)) +
  facet_wrap(~yr ,scales="free_y",ncol=1 )+  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title="New Cases By Day (as of 2024-08-25)")
```

# Total and Daily Deaths Worldwide by Date

```{r}
world |> ggplot() + geom_line(aes(x=date,y=total_deaths)) +

  labs(title="Total Monkey Pox Deaths Worldwide") +
   theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}
world |> ggplot() + geom_line(aes(x=date,y=new_deaths)) +
  facet_wrap(~yr,scales="free_y",ncol=1) +  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title="New Deaths By Day (as of 2024-08-25)")

```

# Running totals by Year and Date

```{r}

running_total <- world %>%
  group_by(yr) %>%
  arrange(date) %>%  # Ensure data is sorted by date within each year
  mutate(
    running_cases = cumsum(new_cases),
    running_deaths = cumsum(new_deaths)
  ) %>%
  ungroup()

running_total$yr <- as.factor(running_total$yr)
```
```{r}
running_total |> ggplot() + geom_area(aes(x=date,y=running_cases,col=yr,fill=yr),linewidth=2) +
  labs(title="Cumulative Total New Cases by Year/Date")

running_total |> ggplot() + geom_area(aes(x=date,y=running_deaths,col=yr,fill=yr),linewidth=2) +
  labs(title="Cumulative Total New Deaths by Year/Date")
```

# Extract Total And Daily Cases by Continent

```{r}
continents <- monkey |> filter(is.na(iso_code)& location != "World")
```

```{r}
continents |> count(location,sort=TRUE) |>
  ggplot() + geom_col(aes(x = reorder(location, n), y = n, fill = location)) + 
  coord_flip() + 
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank()) +
  labs(title="Count of Dates Reported by Continent",y="Dates Reported")
```

```{r}
continents |> ggplot() + 
  geom_line(aes(x=date,y=total_cases,col=location),linewidth=2) +
  labs(title="Total Monkey Pox Cases by Continent")
```

```{r}
continents |> ggplot() + 
  geom_line(aes(x=date,y=new_cases,col=location),linewidth=2) +
  labs(title="Daily Monkey Pox Cases by Continent")
```

# Total And Daily Deaths by Continent

```{r}
continents |> ggplot() + 
  geom_line(aes(x=date,y=total_deaths,col=location),linewidth=2) +
  labs(title="Total Monkey Pox Deaths by Continent")

continents |> ggplot() + 
  geom_line(aes(x=date,y=new_deaths,col=location),linewidth=2) +
  labs(title="Daily Monkey Pox Deaths by Continent")
```

```{r}
continents |> ggplot() + 
  geom_line(aes(x=date,y=total_deaths,col=location),linewidth=2) +
  labs(title="Total Monkey Pox Deaths by Continent") +
  facet_wrap(~location)

continents |> ggplot() + 
  geom_line(aes(x=date,y=new_deaths,col=location),linewidth=2) +
  labs(title="Daily Monkey Pox Deaths by Continent") +
  facet_wrap(~location)
```

# Top Five Countries by Total Cases or Deaths

```{r}
countries <- monkey |> filter(!is.na(iso_code))
top_five <- countries |> filter(date =='2024-08-25')
```